# Generated by Django 4.1.5 on 2023-01-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_description_task_description_task_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
